### ISSUE TITLE
请问有详细一点的文档嘛

### ISSUE THREAD

**Issue by Lu-Lucifer** [SW-Fantastic/note#11]
最后一步说加--add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls后运行还是有问题，
![image](https://user-images.githubusercontent.com/29009277/95674888-cd9d8180-0be5-11eb-9128-6d84286622cc.png)
出现这个问题，要怎么弄才能运行啊

**Comment by SW-Fantastic** [comment]
有人在看啊，我很意外呢，这个问题看起来是javafx的问题，你检查一下maven是不是有引入失败的地方，建议删除m2目录里面的javafx相关文件夹，然后重新导入工程试试，因为找不到符号通常意味着缺少相关的类库，可能是maven的一部分下载失败了。

另外这个东西我在重新编写里面的一部分代码，因为直接使用h2和hibernate存储数据性能是在不怎么样。

**Comment by SW-Fantastic** [comment]
C:\Users\lenovo\.m2\repository\org\openjfx
windows系统的maven目录里面，这里就是javafx的位置了，删掉它重新导入看看，然后建议在运行之前先执行mvn clean清理一下，防止有奇怪的错误，附上我的idea配置：
![image](https://user-images.githubusercontent.com/36193170/101238386-de1c3500-371a-11eb-8957-dc11e5498775.png)
从这个菜单里面选择run maven goal
![image](https://user-images.githubusercontent.com/36193170/101238403-f8eea980-371a-11eb-8a8c-d5ce1f2925b5.png)
如下图添加
![image](https://user-images.githubusercontent.com/36193170/101238421-14f24b00-371b-11eb-8f8b-54c0a59a89cd.png)
然后上移到build之前。

关于文档，这个还有很多功能没做完，所以一直没写，javafx的框架也是我自己做的，有些地方比较繁琐，我准备在完善一些之后出文档。

**Comment by Lu-Lucifer** [comment]
@SW-Fantastic 多谢大佬
